### ISSUE TITLE
Test Dataset "test_015_Sord_video_Q01_done/imgs/00000492.png" corrupted

### ISSUE THREAD

**Issue by LeoHsuProgrammingLab** [wangxiao5791509/TNL2K_evaluation_toolkit#27]
The image is broken.
With the error message "libpng error: IDAT: invalid code lengths set".

**Comment by wangxiao5791509** [comment]
@LeoHsuProgrammingLab  Please check the News in the readme for this image 

2022.04.17 Update the damaged image on BaiduYun: test_015_Sord_video_Q01_done\00000492.png [[link](https://github.com/wangxiao5791509/TNL2K_evaluation_toolkit/blob/main/00000492.png)]

**Comment by LeoHsuProgrammingLab** [comment]
Thank you for replying!
I cannot access the data from Baidu. Instead, the dataset from the OneDrive link hasn't been updated. 

Thank you again!
