### ISSUE TITLE
Code of TNL2K algorithm

### ISSUE THREAD

**Issue by amirhamidihd** [wangxiao5791509/TNL2K_evaluation_toolkit#3]
Hi dear Wang,
Do you have any plan to release the code of the "Towards More Flexible and Accurate Object Tracking with Natural Language" algorithm?
Thanks.

**Comment by wangxiao5791509** [comment]
@amirhamidihd  Hi, thanks for your interest in our work. We will release the code when the journal extension is done.

**Comment by amirhamidihd** [comment]
Thanks.
