### ISSUE TITLE
How can I get precision plots?

### ISSUE THREAD

**Issue by lawpdas** [wangxiao5791509/TNL2K_evaluation_toolkit#5]
When I set `norm_dst=true, ranking_type='AUC'`, it can generate Norm.Prec plots and Succ. plots, which are the same as the plots of your paper.
But Prec. plots is different, when I set `norm_dst=false, ranking_type='threshold'`.
The score of SiamRCNN is 0.528 in your paper, but I got 0.561.
However, I found that the score of `Ours` is the same as that reported in your paper.
![error_OPE_threshold_error](https://user-images.githubusercontent.com/5070053/119634965-cf9b1480-be45-11eb-835e-b2fa8bbf09ab.png)

**Comment by wangxiao5791509** [comment]
@lawpdas   Thanks for your feedback. Can you add my wechat and discuss on this issue for detail? my wechat is **wangxiao5791509**.
