### ISSUE TITLE
The result comparison

### ISSUE THREAD

**Issue by Tchuanm** [wangxiao5791509/TNL2K_evaluation_toolkit#6]
Nice work. Are  Siam R-CNN and other trackers only tested on TNL2k or tested after trained?   
For results of Tracking by Bounding Box Only.

**Comment by wangxiao5791509** [comment]
@Tchuanm   Hi, thanks for your attention. These trackers are tested with the models released by the authors.

**Comment by Tchuanm** [comment]
Thank you for your prompt reply
